#!/usr/bin/env python3
"""Export a trained actor network to a dependency-free C header and to JSON.

The header contains the observation normaliser and the MLP weights plus a
``drone_policy_forward(obs, action)`` function, so the same network can run on
an ESP32 / STM32 / Teensy next to a real MPU-6050.

    python scripts/export_policy.py runs/f450/best.pt --out export/
"""
import argparse
import json
from pathlib import Path

import numpy as np
from common import make_model  # noqa: F401  (sets up sys.path)

from drone_sim.rl import Policy

OBS_LAYOUT = [
    "0-8   R_est (row-major, body->world) from the Mahony filter",
    "9-11  gyro [rad/s] / pi (MPU-6050 GYRO_*OUT / LSB-per-rad/s)",
    "12-14 accel [m/s^2] / 9.80665 (MPU-6050 ACCEL_*OUT)",
    "15-17 target - position [m], world frame, clipped to +-2",
    "18-20 velocity [m/s] / 2, world frame",
    "21-24 previous action",
]


def c_array(name, arr):
    flat = ", ".join(f"{v:.8e}f" for v in np.asarray(arr, np.float32).ravel())
    return f"static const float {name}[{np.asarray(arr).size}] = {{{flat}}};\n"


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("checkpoint")
    p.add_argument("--out", default="export")
    a = p.parse_args()
    pol = Policy.load(a.checkpoint)
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    layers = [m for m in pol.net.actor if hasattr(m, "weight")]
    mean, std = pol.obs_rms.mean, np.sqrt(pol.obs_rms.var + 1e-8)

    h = ["/* Auto-generated by export_policy.py -- neural flight controller */",
         "#pragma once", "#include <math.h>", "",
         "/* Observation layout (25 floats):", *[f" *   {s}" for s in OBS_LAYOUT], " *",
         " * Action (4 floats, [-1, 1]) per motor (0 FL, 1 RL, 2 RR, 3 FR):",
         f" *   thrust fraction = a<0 ? h*(1+a) : h + a*(1-h),  h = {pol.drone_model().hover_thrust_fraction():.5f}",
         " */", "", f"#define DRONE_OBS_DIM {mean.size}", "#define DRONE_ACT_DIM 4", ""]
    h.append(c_array("drone_obs_mean", mean))
    h.append(c_array("drone_obs_std", std))
    h.append(f"static const float drone_obs_clip = {pol.obs_rms.clip:.1f}f;\n")
    for i, L in enumerate(layers):
        h.append(c_array(f"drone_W{i}", L.weight.detach().numpy()))
        h.append(c_array(f"drone_b{i}", L.bias.detach().numpy()))
    sizes = [layers[0].in_features] + [L.out_features for L in layers]
    maxw = max(sizes)
    body = ["static inline void drone_policy_forward(const float *obs, float *action) {",
            f"    float a[{maxw}], b[{maxw}];",
            "    for (int i = 0; i < DRONE_OBS_DIM; ++i) {",
            "        float v = (obs[i] - drone_obs_mean[i]) / drone_obs_std[i];",
            "        a[i] = v > drone_obs_clip ? drone_obs_clip : (v < -drone_obs_clip ? -drone_obs_clip : v);",
            "    }"]
    for i in range(len(layers)):
        n_in, n_out = sizes[i], sizes[i + 1]
        last = i == len(layers) - 1
        src, dst = ("a", "b") if i % 2 == 0 else ("b", "a")
        body += [f"    for (int o = 0; o < {n_out}; ++o) {{",
                 f"        float s = drone_b{i}[o];",
                 f"        for (int k = 0; k < {n_in}; ++k) s += drone_W{i}[o * {n_in} + k] * {src}[k];",
                 f"        {dst}[o] = {'s' if last else 'tanhf(s)'};", "    }"]
    final = "b" if (len(layers) - 1) % 2 == 0 else "a"
    body += ["    for (int o = 0; o < DRONE_ACT_DIM; ++o) {",
             f"        float v = {final}[o];",
             "        action[o] = v > 1.f ? 1.f : (v < -1.f ? -1.f : v);", "    }", "}"]
    (out / "drone_policy.h").write_text("\n".join(h + body) + "\n")
    js = {"obs_mean": mean.tolist(), "obs_std": std.tolist(), "obs_clip": pol.obs_rms.clip,
          "layers": [{"W": L.weight.detach().numpy().tolist(), "b": L.bias.detach().numpy().tolist()} for L in layers],
          "activation": "tanh", "obs_layout": OBS_LAYOUT}
    (out / "drone_policy.json").write_text(json.dumps(js))
    print(f"wrote {out/'drone_policy.h'} and {out/'drone_policy.json'} "
          f"({sum(L.weight.numel() + L.bias.numel() for L in layers)} parameters)")


if __name__ == "__main__":
    main()
